### ISSUE TITLE
GLFW and OpenGL initialization issue

### ISSUE THREAD

**Issue by dcronqvist** [biffbaff64/LughSharp#2]
### Problem 1: Initialization order

There's currently an issue with the creation of a window which involves setting up GLFW and OpenGL properly. As it currently stands, `DesktopGLApplication.cs` attempts to initialize OpenGL before GLFW which is not possible as it requires an existing and bound OpenGL context, which is created by GLFW.

#### Solution: Initialize GLFW first and then initialize OpenGL

Modify part of the constructor in `DesktopGLApplication` here:
https://github.com/biffbaff64/LughSharp/blob/4931e68c236485d853a70c8fac8d3f7e47389d9d/Backends/DesktopGL/DesktopGLApplication.cs#L121-L126

to instead look like this:
```c#
// GLFW initialisation
InitialiseGLFW();

// Create the window(s)
Windows.Add( CreateWindow( config, listener, 0 ) );
```

In addition to this, you must call `InitialiseGL` after `MakeContextCurrent`. Modify here:
https://github.com/biffbaff64/LughSharp/blob/4931e68c236485d853a70c8fac8d3f7e47389d9d/Backends/DesktopGL/DesktopGLApplication.cs#L471-L476

to:
```c#
  Glfw.MakeContextCurrent( windowHandle );
  Glfw.SwapInterval( config.VSyncEnabled ? 1 : 0 );

  Logger.CheckPoint();

  InitialiseGL();
  InitGLVersion();
```

### Problem 2: Invalid OpenGL version requested

In a consumer project of LughSharp, the following code will result in configuring an invalid OpenGL version:
```c#
var config = new DesktopGLApplicationConfiguration
{
    Title         = "LughSharp Template",
    VSyncEnabled  = true,
    ForegroundFPS = 60,
    DisableAudio  = true
};

config.SetWindowedMode( 640, 480 );

var game = new DesktopGLApplication( new MainGame(), config );
game.Run();
```

#### Solution 1: consumer specifies the OpenGL version

One must make sure to call `config.SetGLContextVersion()` at some point before calling the `DesktopGLApplication` constructor to make sure that the configuration does not have version **0.0** set. Alternatively, the consumer can excplicitly set the `GLContextVersionMajor` and minor in the initialization list of the configuration.

#### Solution 2: add default values to `GLContextVersionMajor` and `GLContextVersionMinor`

Another alternative might be to provide default values to the `GLContextMajorVersion` and `GLContextMinorVersion` instead of having ways to get the consumer to end up in a strange state. Example:

https://github.com/biffbaff64/LughSharp/blob/4931e68c236485d853a70c8fac8d3f7e47389d9d/Backends/DesktopGL/DesktopGLApplicationConfiguration.cs#L55-L58

is modified to:

```c#
public int GLContextMajorVersion { get; set; } = DEFAULT_CONTEXT_MAJOR;
public int GLContextMinorVersion { get; set; } = DEFAULT_CONTEXT_MINOR;
```

These solutions should resolve the above listed GLFW and OpenGL initialization issues.

**Comment by biffbaff64** [comment]
Thanks Daniel, I've updated to this now. It's definitely getting further.

**Comment by dcronqvist** [comment]
Great! Feel free to close this issue whenever you commit and merge the related changes to keep a clean issue-inbox :)
